### ISSUE TITLE
Doesn't search notes recursively.

### ISSUE THREAD

**Issue by vinoff** [omarcospo/dumbnotes.nvim#1]
If your Notes folder is a main folder with several other sub-folders, DumbNotes doesn't work.

For example:

notes_path = "~/Notes", -- Path to the notes directory

And then, Notes has "Math", "Chemistry", "Programming" subfolders. Each of these subfolders has the .md notes files. Dumbnotes does not work in this case.

**Comment by mfxarc** [comment]
I added an option to find notes recursively, just call setup with `find_recursively = true`
``` lua
require("dumbnotes").setup({
  find_recursively = true,
})
```
You should be able to create notes in your desired folder with the new_note_key and inserting:
`"{Folder}/{Name of note}"`.

**Comment by vinoff** [comment]
> I added an option to find notes recursively, just call setup with `find_recursively = true`
> 
> ```lua
> require("dumbnotes").setup({
>   find_recursively = true,
> })
> ```
> 
> You should be able to create notes in your desired folder with the new_note_key and inserting: `"{Folder}/{Name of note}"`.

I just tried it. Thank you. 

EDIT: I forgot to update the plugin. It works perfectly now. Thank you.

**Comment by vinoff** [comment]
It would be nice to have tab completion when creating a new note.. I can't remember the names of the folders. So, if I want to create a note on FolderABC/newNote.md, it would be nice to type "Folder" +tab and have it autocomplete to FolderABC.. Or some way to see which folders I have..

**Comment by mfxarc** [comment]
I'm closing this issue as I see it been fixed, and I created a new issue for the completion feature.
